---
- name: Deploy Scientific Calculator Container
  hosts: localhost

  tasks:

    - name: Pull latest image
      docker_image:
        name: raghav2805/scientific_calculator
        source: pull

    - name: Stop old container
      docker_container:
        name: scientific_calculator
        state: stopped
      ignore_errors: yes

    - name: Remove old container
      docker_container:
        name: scientific_calculator
        state: absent
      ignore_errors: yes

    - name: Run new container
      docker_container:
        name: scientific_calculator
        image: raghav2805/scientific_calculator
        state: started
        tty: true
        interactive: true
