---
- name: Deploy Scientific Calculator Container
  hosts: localhost
  become: false

  vars:
    image_name: "raghav2805/scientific_calculator"
    container_name: "scientific_calculator"

  tasks:

    - name: Pull latest Docker image
      docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Stop existing container
      docker_container:
        name: "{{ container_name }}"
        state: stopped
      ignore_errors: yes

    - name: Remove existing container
      docker_container:
        name: "{{ container_name }}"
        state: absent
      ignore_errors: yes

    - name: Create new container (do not start)
      docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: present
        tty: true
        interactive: true
